# Generated by Django 5.2.7 on 2025-11-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('user', 'project', 'date')},
        ),
    ]
