# Generated by Django 5.2.7 on 2025-11-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_timeentry_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together=set(),
        ),
    ]
