# Generated by Django 5.2.7 on 2025-11-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_timeentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-date', '-created_at'], 'verbose_name_plural': 'Time_entries'},
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('user', 'project', 'date')},
        ),
    ]
