# Generated by Django 5.2.7 on 2025-11-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_timeentry_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together=set(),
        ),
    ]
