# Generated by Django 5.2.7 on 2025-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_timeentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.IntegerField(),
        ),
    ]
