# Generated by Django 5.2.7 on 2025-11-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_alter_timeentry_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='role',
            field=models.CharField(choices=[('executor', 'Исполнитель'), ('reviewer', 'Проверяющий'), ('consultant', 'Консультация')], default='executor', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('user', 'project', 'hours')},
        ),
    ]
