# Generated by Django 5.2.7 on 2025-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_timeentry_description_alter_timeentry_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_overtime',
            field=models.BooleanField(default=False, help_text='Овертайм', verbose_name='Овертайм'),
        ),
    ]
