# Generated by Django 5.2.7 on 2025-11-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_timeentry_is_overtime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('user', 'project', 'date', 'hours')},
        ),
    ]
