# Generated by ChatGPT on 2025-11-06

from decimal import Decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_timeentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hours',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    MinValueValidator(Decimal('0.25')),
                    MaxValueValidator(Decimal('24')),
                ],
            ),
        ),
    ]
